version: '3.8'

services:
  backend:
    build: ./backend
    container_name: notscrum-backend
    volumes:
      - ./backend:/app
      - notscrum_sqlite_data:/app/instance
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # Change the command to make sure flask keeps running
    command: >
      sh -c "chmod +x /app/init_db.sh &&
             ./init_db.sh &&
             flask run --host=0.0.0.0"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/api/boards')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  notscrum_sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:/DEV/NotScrum/docker_volumes/sqlite_data
